// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZF1P_5lyw8sqf0mLNx9mVgJU_1jVjLNQ',
    appId: '1:646016974455:web:b02c89e2773832b1af1072',
    messagingSenderId: '646016974455',
    projectId: 'pokedex-998ae',
    authDomain: 'pokedex-998ae.firebaseapp.com',
    storageBucket: 'pokedex-998ae.appspot.com',
    measurementId: 'G-MECWRJGQSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHAbmuyNrEMyQquWtGnuaTtDjlc9kBpD0',
    appId: '1:646016974455:android:dd8369b2016ce65faf1072',
    messagingSenderId: '646016974455',
    projectId: 'pokedex-998ae',
    storageBucket: 'pokedex-998ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSAVP1P5vw8FiWnGv9AL3s_xKfZOI7aNk',
    appId: '1:646016974455:ios:e8d1c35580da8362af1072',
    messagingSenderId: '646016974455',
    projectId: 'pokedex-998ae',
    storageBucket: 'pokedex-998ae.appspot.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSAVP1P5vw8FiWnGv9AL3s_xKfZOI7aNk',
    appId: '1:646016974455:ios:56462fe783eaf7fdaf1072',
    messagingSenderId: '646016974455',
    projectId: 'pokedex-998ae',
    storageBucket: 'pokedex-998ae.appspot.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
